CREATE TABLE R(A INT, B INT, C INT);

CREATE OR REPLACE TRIGGER PROVA
BEFORE INSERT ON R
REFERENCING NEW AS N
FOR EACH ROW
IF (N.A < 10) THEN 
	SET N.B = 5,
	    N.C = 15;
ELSE
	SET N.B = N.A + 1,
	    N.C = N.A + 3; -- N.C = N.B + 3 dà NULL 
END IF

INSERT INTO R(A) VALUES (:A);

