--
-- Esercitazione 6, esercizio 3
-- 
-- Script SQL di definizione delle table e inserimento di alcuni dati d'esempio

DROP TABLE STUDENTI;
DROP TABLE CORSI;
DROP TABLE APPELLI;
DROP TABLE ESAMI;
DROP TABLE VERBALIZZAZIONI;


CREATE TABLE STUDENTI(
        MATR CHAR(6) NOT NULL PRIMARY KEY,  -- CHAR(6) solo per brevita'
        NOME VARCHAR(30) NOT NULL,
        COGNOME VARCHAR(30) NOT NULL					);

CREATE TABLE CORSI (
        CODC CHAR(3) NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL 					);

CREATE TABLE APPELLI (
        CODC CHAR(3) NOT NULL REFERENCES CORSI,
	DATA DATE NOT NULL, 
	LUOGO VARCHAR(30) NOT NULL,
	PRIMARY KEY (CODC, DATA)					);

CREATE TABLE ESAMI (
	MATR CHAR(6) NOT NULL REFERENCES STUDENTI,
        CODC CHAR(3) NOT NULL,
	DATA DATE NOT NULL, 
	VOTO INT NOT NULL CHECK (VOTO BETWEEN 0 AND 31),
	ACCETTATO CHAR(1) DEFAULT NULL CHECK (ACCETTATO = 'Y'),
	FOREIGN KEY (CODC, DATA) REFERENCES APPELLI,
	PRIMARY KEY (MATR, CODC, DATA)					);

CREATE TABLE VERBALIZZAZIONI (
	MATR CHAR(6) NOT NULL REFERENCES STUDENTI,
        CODC CHAR(3) NOT NULL,
	DATA DATE NOT NULL, 
	VOTO INT NOT NULL CHECK (VOTO BETWEEN 18 AND 31),
	FOREIGN KEY (CODC, DATA) REFERENCES APPELLI,
	PRIMARY KEY (MATR, CODC)					);


-- Inserimenti validi 

INSERT INTO STUDENTI VALUES ('765432', 'Carlo', 'Rubbia');

INSERT INTO CORSI VALUES ('SIT', 'Sistemi Informativi T'), 
			 ('CET', 'Calcolatori Elettronici T');

INSERT INTO APPELLI VALUES ('SIT', '10.02.2019', 'LAB 4'),
			   ('SIT', '22.06.2019', 'LAB 3'),
			   ('CET', '20.01.2019', 'AULA 2.9'),
			   ('CET', '14.07.2019', 'AULA 2.4');


INSERT INTO ESAMI VALUES ('765432', 'SIT', '10.02.2019', 19, NULL),
			 ('765432', 'SIT', '22.06.2019', 27, NULL),
			 ('765432', 'CET', '20.01.2019', 15, NULL),
			 ('765432', 'CET', '14.07.2019', 31, NULL);
